apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thesting12345-gitops
  namespace: orchestrator-gitops
  labels:
    app-type: workflow
    app: thesting12345
    rht-gitops.com/janus-argocd: thesting12345-gitops
spec:
  destination:
    namespace: sonataflow-infra
    server: https://kubernetes.default.svc
  project: orchestrator-gitops
  source:
    path: ./kustomize/base
    repoURL: git@github.com:orchestrator-test/thesting12345-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
